schemas.py
tests/atividade_test.py
tests/plano_trabalho_test.py

Co-authored-by: Augusto Herrmann <augusto+github@herrmann.tech>
fixes #26

fix(plano_trabalho): change date validation to adjusted business rules

---

schemas.py
tests/plano_trabalho_test.py

fix(plano_trablho): remove carga_horaria validation

---

schemas.py
tests/atividade_test.py
tests/plano_trabalho_test.py

fix(schemas): change field mandatority

---

tests/plano_trabalho_test.py

test(performance): add test to insert huge plano_trabalho

---

api.py
crud.py
models.py
tests/atividade_test.py
tests/plano_trabalho_test.py

Os campos agora serão salvos. Inclui também novo teste.

Corrige a atualização da atividade com PUT e PATCH

---

README.md

Novas instruções no README.md. Não foi necessário mudar o código da aplicação.

fixes #38: acrescenta instruções para configurar para usar um bd externo

---

api.py
auth.py
database.py
models.py

Adiciona pelo ORM duas colunas (data de atualização e data de modificação) nas tabelas plano_trabalho, atividades e user. Implementa uma trigger para o postgreSQL em cada tabela para a inserção de dados automática.

Acrescenta no ORM os campos data_atualizacao e data_modificacao

---

bootstrap_app.py
docker-compose.yml

Add script to wait for database to be running

---

Jenkinsfile

* refactors out keys and service id to environment variable
* returns the error level to Jenkins so that a failed Rancher upgrade will fail the Jenkins job
fixes #52

Fix service id and errorlevel in Jenkinsfile

---

api.py
tests/entrypoint_test.py

Co-authored-by: Augusto Herrmann <augusto+github@herrmann.tech>
Co-authored-by: Gutaors <gutaors@gmail.com>
Fix #54

Add redirect root to /docs

---

api.py
email_conf.py

- Fix HTML rendering for email template
- Split email configuration into new file
- Add route to function on_after_reset_password

Fix email rendering and on_after_reset_password

---

docs/description.md

Update front-page description with instructions for resetting password and update user.

Update description with user instructions

---

api.py
auth.py
models.py

Alter object relation mapping columns **cod_unidade** and **cod_unidade_exercicio** from integer to biginteger.
Issue #72

Alter column type to bigint

---

README.md
load_fief_env.sh

Create a bash script for:
- Create a new .env file based on a existing template
- Load the Fief initial configuration with docker run and include the env values on the .env file
Also update the README instructions.

Load fief env

---

src/models.py

add ForeignKeyConstraint for table Entrega

add ForeignKeyConstraint

---

tests/participantes_test.py
tests/plano_entregas_test.py
tests/plano_trabalho_test.py

Adjust status code for creating a resource w/ PUT

---

src/docs/description.md

Remove link and fix mention of endpoints

---

src/schemas.py
tests/plano_trabalho/core_test.py

Remove array participante from Pydantic schema for plano_trabalho

---

tests/conftest.py

Some docstrings were missing, a couple were wrong.

Improve fixtures docstrings in conftest

---

src/crud.py
tests/participantes_test.py

Includes a new test case to verify a condition that was failing before.
Fixes #114

Update participante instead of deleting and re-inserting it

---

src/api.py

Use lifespan instead of event handler to remove deprecation warning

---

release-notes.md
src/models.py
src/schemas.py
tests/participantes_test.py
tests/plano_trabalho/core_test.py

Simplify data validation domains using Enum instead of functions

---

release-notes.md
src/api.py
src/response_schemas.py

Solve pydantic's warnings about deprecated methods .json and .dict

---

release-notes.md
src/docs/description.md

Update allowed values for `modalidade_execucao` in the docs

---

.github/workflows/ci_tests.yml
docs/examples/create_user_example.py
docs/examples/get_all_users_example.py
docs/examples/get_token_example.py
docs/examples/get_user_example.py
release-notes.md

Update examples of API usage in the documentation

---

.github/workflows/ci_tests.yml
release-notes.md
src/api.py

(and solve a mypy type annotation warning)
Fix #166

Set a default of 30 for access token expiration

---

src/api.py
tests/user_test.py

Allow user to fetch their own data with `GET /user/{email}` 

---

release-notes.md
src/models.py

Change all unit types to BigInteger

---

src/models.py
src/schemas.py
tests/conftest.py
tests/participantes_test.py
tests/plano_entregas/core_test.py
tests/plano_trabalho/core_test.py

- Update remaining unit type from Integer to BigInteger in models
- Update Pydantic schema constants for maximum integer values
- Update conftest
fix #191

Update fields to BigInteger

---

src/schemas.py
tests/plano_entregas/date_validation_test.py
tests/plano_trabalho/date_validation_test.py

fix #202 
- Fix the argument order in the over_a_year function call.
- Fix the tests to properly check for year overlap.

Fix over_a_year checks

---

src/docs/description.md
src/schemas.py
tests/conftest.py
tests/data/participante.json
tests/data/plano_entregas.json
tests/data/plano_trabalho.json
tests/participantes_test.py
tests/plano_entregas/core_test.py
tests/plano_entregas/date_validation_test.py
tests/plano_trabalho/core_test.py
tests/plano_trabalho/date_validation_test.py

- Reject Plano de Trabalho with **data_inicio** before 2023-07-31
- Reject Participante with **data_assinatura_tcr** before 2023-07-31
- Create tests for new rule and fix older tests
- Update documentation
Fix #210

Reject Plano de Trabalho and Participante with date before 2023-07-31
