api.py, schemas.py, test_api.py
Ao fazer PUT `/plano_trabalho/{cod_plano}`, aplicar comportamentos diferentes. Caso não exista no banco, será um *create*. Caso não exista, será um *update*. No *create*, devem ser passados os parâmetros obrigatórios. No *update*, eles podem ser omitidos: nesse caso, eles não serão alterados pelo *update*.
Considerar, no futuro, mudar esse comportamento de update parcial para o verbo PATCH, e deixar o PUT apenas para update com os dados completos.
=> Aplica lógicas diferentes para o create e para o update plano de trabalho

api.py, schemas.py, test_api.py
PUT é para o recurso completo; PATCH pode ser uma atualização parcial, enviando apenas os campos que serão alterados.
Já está implementado e com testes. Se concordar com esse requisito, é só aceitar o PR.
=> fixes #7 separa a funcionalidade do PUT e PATCH

admin_tool.py, api.py, auth.py, crud.py, database.py, models.py, schemas.py, test_api.py, util.py
Implementa #1 e #5. Ainda falta implementar que os campos obrigatórios funcionem como obrigatórios e os opcionais funcionem como opcionais para as atividades dentro do plano de trabalho.
Atentar para a diferença de funcionamento entre PUT e PATCH. O primeiro cria ou substitui. O último altera os campos informados e ignora os campos não informados.
Testes:
Implementação:
=> testes e implementação para campos opcionais e obrigatórios de atividades

docker-compose.yml
O comando modificado no container web faz esperar a porta do Postgres estar aberta.
=> Resolve a race condition entre containers

README.md
Me ocorreu a percepção de que uma pessoa que chegar a este repositório, na falta de uma contextualização, e ler o README, não entenderá para que serve a API. Proponho incluir uma breve contextualização para que as pessoas tenham uma ideia melhor de que se trata o projeto.
=> acrescenta uma contextualização na descrição do projeto

schemas.py
Está no modelo e na base de dados, mas não no `schema.py`. Com isso, explicamos melhor o motivo.
=> fixes #34: explain why cod_unidade is not in schema.py

.github/workflows/docker-image.yml, .gitignore, Dockerfile, README.md, admin_tool.py, database.py, docker-compose.yml
O nome de usuário, senha e nome do banco agora são passados como variáveis de ambiente. Para executar no `docker-compose`, é necessário criar um arquivo `.env`, informando esses parâmetros, conforme explicado no `README.md`.
=> fixes #28: separa as strings de conexão ao banco em um arquivo .env

api.py, models.py, schemas.py, tests/conftest.py, tests/plano_trabalho_test.py
Os testes estão passando e esta alteração já pode ser incorporada.
@henrique-prog, gostaria de incluir uma descrição para o campo `situacao`? Talvez definir quais são os valores aceitos, ou pelo menos sugeridos? Ou é para deixar livre, mesmo? Por enquanto, está livre e o preenchimento do campo é opcional.
=> inclui o campo situacao no plano de trabalho

api.py
Conforme solicitado pela gestão do sistema, os métodos `user` serão novamente expostos.
=> Expõe novamente o método users na documentação swagger

.github/workflows/docker-image.yml, docker-compose.yml, run_after_db.py
Added a generic Python script that will wait the the database to be online and then run any command afterward.
This is used both for starting the application as well as running the CI tests.
Fixes #60
=> Implement running CI script after waiting for db

api.py, tests/entrypoint_test.py
Access to the root (`.`) will redirect to a different url depending on content negotiation. Browsers requesting html will be redirected to `/docs`, scripts requesting json will be redirected to `/openapi.json`.
Fixes #61
=> Implements redirection based on http conneg

docker-compose.yml, requirements.txt, src/api.py, src/crud_auth.py, src/email_config.py, tests/conftest.py, tests/user_test.py
Implement reset password function in API:
- Introduce a new **smtp4dev** container for development deployment in docker-compose
- Include **fastapi-mail 1.4.1** in _requirements.txt_
- Establish the _email_config.py_ file containing SMTP environment variables and email templates.
- Develop methods for **forgot password** (sending a email to the user with a token) and **reset password** (resetting the password using the token)
- Create tests for forgot_password
TODO: 
- Create tests for reset_password (needs to catch the token in the email body)
=> Implement forgot/reset password endpoints

src/api.py, src/create_admin_user.py, src/crud_auth.py, src/email_config.py, src/models.py, src/schemas.py, src/util.py, tests/entrypoint_test.py, tests/participantes_test.py, tests/plano_entregas_test.py, tests/plano_trabalho_test.py
According to requisites file defined by stakeholder, some fields were defined as mandatory.
In `models.py` they were indeed `nullable=False`, but in `schemas.py` they were defined as optional. We made it consistent by making it mandatory there too.
Some new tests were added for making sure that optional fields can be included with a json value of `null`.
Fixes #95
=> Make some fields in Entrega mandatory and add some tests

docs/gestao-de-usuarios.md
Acrescenta um novo documento markdown orientando como cadastrar e alterar cadastro de usuários.
Resolve #83
=> Acrescenta documentação sobre a gestão de usuários

src/schemas.py, tests/participantes_test.py, tests/plano_entregas/core_test.py
=> Use Pydantic's native data types and handle timezone-aware datetimes

tests/participantes_test.py, tests/plano_entregas/core_test.py, tests/plano_entregas/date_validation_test.py, tests/plano_entregas/permissions_test.py, tests/plano_trabalho/avaliacao_registros_execucao_test.py, tests/plano_trabalho/contribuicoes_test.py, tests/plano_trabalho/core_test.py, tests/plano_trabalho/date_validation_test.py, tests/plano_trabalho/permissions_test.py
Remove code redundancy and simplify maintenance by refactoring isolated test functions into test classes that contain similar tests.
=> Refactor tests for Plano de Trabalho and Participante to use pytest classes

src/models.py, src/schemas.py, tests/participantes_test.py
=> Make `data_assinatura_tcr` not nullable

src/api.py, src/crud_auth.py, src/response_schemas.py, src/schemas.py, tests/user_test.py
=> Corrigir documentação da OpenAPI para mostrar os códigos de status HTTP que de fato podem ser retornados

src/schemas.py
=> Change data type of origem_unidade in Pydantic to Enum

release-notes.md, src/docs/description.md, src/models.py
Add the requested text in the API and `cod_unidade_autorizacao` field descriptions.
Fix #135.
=> Add additional explanation about cod_unidade_autorizacao

release-notes.md, src/api.py, src/crud_auth.py, tests/conftest.py, tests/participantes_test.py, tests/plano_entregas/core_test.py, tests/plano_entregas/date_validation_test.py, tests/plano_entregas/permissions_test.py, tests/plano_trabalho/avaliacao_registros_execucao_test.py, tests/plano_trabalho/contribuicoes_test.py, tests/plano_trabalho/core_test.py, tests/plano_trabalho/date_validation_test.py, tests/plano_trabalho/participante_outra_lotacao_test.py, tests/plano_trabalho/permissions_test.py, tests/user_test.py
* Speed up test suite by changing the scope of fixtures
* Use deep copy in tests to avoid interference in other tests
* Block users that have been disabled from logging in
Fix #134
=> Disallow disabled users from logging into the application

release-notes.md, src/crud_auth.py, tests/conftest.py, tests/user_test.py
=> Handle error when attempting to log in with a non-existing user

release-notes.md, src/crud.py, tests/plano_trabalho/contribuicoes_test.py
Fix #152 
Corrige a iteração em lista quando o valor json `null` é passado no campo `contribuicoes` do `plano_trabalho`. Estava gerando erro HTTP 500 para algumas entradas.
=> Tratar adequadamente quando o valor null é passado no campo contribuicoes do plano_trabalho

release-notes.md, src/crud.py, tests/plano_trabalho/contribuicoes_test.py, tests/plano_trabalho/core_test.py
Fix #154 
Corrige a iteração em lista quando o valor json `null` é passado em qualquer campo opcional do `plano_trabalho` que pode ser uma lista. Estava gerando erro HTTP 500 para algumas entradas.
=>  Tratar adequadamente quando o valor null é passado em campos opcionais que podem ser listas

release-notes.md, src/schemas.py, tests/conftest.py, tests/participantes_test.py, tests/plano_entregas/core_test.py, tests/plano_trabalho/core_test.py
=> Check for integer ranges in input validation for participante, plano_trabalho and plano_entregas

release-notes.md, src/crud.py, tests/participantes_test.py
Fix #140
Solve SQL Alchemy's warnings about absence of PlanoTrabalho in session, in context of the relationship with Participante.
=> Solve SQL Alchemy's warnings about absence of PlanoTrabalho in session

src/models.py, tests/participantes_test.py
=> Add tests and documentation for the `date` and `datetime` formats accepted for `data_assinatura_tcr` of `participante`

release-notes.md, src/api.py, src/crud.py, src/models.py, src/schemas.py, tests/conftest.py, tests/plano_trabalho/contribuicoes_test.py, tests/plano_trabalho/date_validation_test.py
A `Contribuicao` já possui o campo `id_contribuicao` que pode ser usado como identificador da contribuição em cada sistema do órgão. O campo `id` é interno do banco de dados e não deve ser exposto na API.
Fix #165
=> Retira o campo id da Contribuicao

release-notes.md, src/api.py, src/models.py, tests/endpoints_test.py
Adiciona cabeçalho [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (CSP), definindo de onde os recursos podem ser carregados pelo navegador, às páginas de documentação (`/docs` na Swagger UI e `/redoc` na ReDoc).
As demais rotas não são feitas para ser acessadas por navegadores e por isso não faz diferença existir CSP.
Fix #144
=> Adiciona cabeçalho Content-Security-Policy às páginas de documentação

release-notes.md, src/api.py, tests/endpoints_test.py
to allow indexing of just the documentation by search engines.
Fix #172
=> Add a robots.txt file

release-notes.md, src/api.py, src/db_config.py, src/models.py
=> Handle several database outage situations gracefully, add database health check endpoint

migration/3.2.7.sql
The script will help migrating existing installations of the application from version 3.2.6 to 3.2.7.
=> Add database migration script for 3.2.7

release-notes.md, src/crud.py, src/models.py, tests/data/plano_trabalho.json, tests/plano_trabalho/core_test.py, tests/plano_trabalho/date_validation_test.py
Fix #183
Validation rule requested by stakeholder.
=> Add validation for `data_inicio` of `PlanoTrabalho`, must be equal to or greater than `data_assinatura_tcr` of Participante

src/crud.py, src/models.py, tests/plano_trabalho/date_validation_test.py
- Remove validation on CRUD (if data_assinatura_tcr > data_inicio)
- Adjust field description on models
- Remove data_assinatura_tcr fixture and validation on Plano de Trabalho tests
=> Remove data_assinatura_tcr validation (greater than data_inicio of Plano de Trabalho)

Dockerfile, docker-compose.yml
- Remove flag _--reload_ on docker build process.
- Override entrypoint on docker-compose file adding flag _--reload,_ for local development. When using docker-compose up, it will override the entrypoint defined in the Dockerfile.
Fix #182
=> Remove flag reload on image build

src/docs/description.md, src/schemas.py, tests/plano_entregas/core_test.py
Fix #198 
Allow the meta_entrega value to exceed 100 when in percent mode.
- Remove the rule from the documentation.
- Remove the validation from Pydantic.
- Adjust the Plano Entrega tests for meta_entrega.
=> Allow meta_entrega greater than 100 when percent mode

src/docs/description.md, src/schemas.py, tests/plano_entregas/core_test.py
Fix #200 
- Include a warning in the documentation.
- Create a Pydantic validation to reject empty "Entregas" when submitting "Plano de Entregas", except when the status equals 1.
- Update the test_create_plano_entregas_sem_entregas test.
=> Create validation for empty Entregas list

src/docs/description.md, src/models.py, src/schemas.py, tests/participantes_test.py, tests/plano_entregas/core_test.py, tests/plano_trabalho/core_test.py, tests/user_test.py
Fix #204 
- Implement length validation for _cod_unidade_autorizadora_ based on origem_unidade (SIAPE or SIORG).
- Create tests for invalid cod_unidade_autorizadora values in **Participantes**, **Plano de Entregas** and **Users**
- Add pydantic validation rule in _schemas_
- Update existing tests based on this new validation rule.
=> Implement length validation for cod_unidade_autorizadora based on origem_unidade

src/crud.py
fix #215 
- Implement transaction mode using session.begin() in update_plano_trabalho and update_plano_entregas to ensure data consistency.
- Create helper function _build_model_plano to encapsulate shared logic between create and update operations, improving code reusability.
=> Add transactional support in update_plano_trabalho and update_plano_entregas

docker-compose.yml, src/api.py, src/db_audit.py, src/db_config.py
Fix #216 
- Create a function to set up the audit schema and table
- Add triggers to API tables to log inserts, updates, and deletes in all api tables
- Set the default value of _TEST_ENVIRONMENT_ to **true** in the Docker Compose file
=> Add audit schema and triggers for API tables

src/crud.py
fix #220 
- Add session.flush() to push changes to DB before ending transaction block
- Place session.refresh outside the session.begin() block to avoid persitent instance errors
=> Refactor update_planos to ensure proper transaction handling
